# Generated by Django 4.1.4 on 2022-12-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_productvisit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='id_delete',
            new_name='is_delete',
        ),
    ]
