# Generated by Django 4.1.4 on 2022-12-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد صفحه'),
        ),
        migrations.AddField(
            model_name='product',
            name='print_version',
            field=models.IntegerField(blank=True, null=True, verbose_name='نسخه چاپ'),
        ),
    ]
