# Generated by Django 4.1.4 on 2022-12-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
