# Generated by Django 4.1.4 on 2022-12-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_alter_order_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='کد پیگیری'),
        ),
    ]
