# Generated by Django 4.1.4 on 2022-12-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_footerlinkbox_alter_sitesetting_about_us_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='about_us_text',
            field=models.TextField(verbose_name='متن درباره ما سایت'),
        ),
    ]
